version: '3.8'
services:
  hotel:
    build:
      context: ./hotel
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=hotel_db
      - DB_USER=admin
      - DB_PASSWORD=admin@123
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
    command: npm run dev

  room:
    build:
      context: ./room
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=hotel_db
      - DB_USER=admin
      - DB_PASSWORD=admin@123
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
    command: npm run dev

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOTEL_SERVICE_URL=http://hotel:3001
      - ROOM_SERVICE_URL=http://room:3002
    depends_on:
      - hotel
      - room
    command: npm run dev 